services:
  php:
    image: php:apache
    volumes:
      - "./:/var/www/html"
    ports:
      - 8000:80
      - 443:334
    
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=webprogramming
      - MYSQL_USER=sunny
      - MYSQL_PASSWORD=admin
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306